### ISSUE TITLE
slow auto complete

### ISSUE THREAD

**Issue by issadarkthing** [octaltree/cmp-look#3]
The auto-completion is slow due to the hefty amount of results returned by `look` command. As mentioned by the author of [nvim-cmp](https://github.com/hrsh7th/nvim-cmp) too much result may make the auto completion slow. As a workaround, we can reduce the results returned by `look` command by passing at least two characters as argument.

One character will return 13k results
```sh
$ look s | wc -l
13624
```

Two characters will return 1k results
```sh
$ look sa | wc -l
1213
```

As a solution, I think we can trigger the auto-complete on at least two characters. This significantly improves the response time and make it more bearable to type.
```lua
M.get_keyword_pattern = function()
  return [[\w\{2,}]]
end
```

**Comment by octaltree** [comment]
I hard-coded 2 for now.

**Comment by p0da** [comment]
It seems that the plugin does not work at all for me unless I remove that check.

**Comment by octaltree** [comment]
Thank you. Now it's configurable from `keyword_length`.
8763244ecf04e1a2bc65408e27dc8344ca95c8e5
